config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'friends#index'
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friend_path, notice: "Not authorized to edit this" if @friend.nil?
  end
  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%=form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <div class="field form-group">
    <%=form.text_field :first_name, class:"form-control",placeholder:"First name" %>
  </div>
  <div class="field form-group">
    <%=form.text_field :last_name, class:"form-control", placeholder:"Last name"%>
  </div>
  <div class="field form-group">
    <%=form.text_field :email, class:"form-control", placeholder:"email@domain.com" %>
  </div>
  <div class="field form-group">
    <%=form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
  </div>
  <div class="field form-group">
    <%=form.text_field :twitter, class:"form-control", placeholder:"Twitter username" %>
  </div>
  <div class="actions">
    <%= form.submit class:'btn btn-dark' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing friend</h1>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
    <br>
    <div>
      <%= link_to "Show", @friend,  class: "btn btn-dark"  %>
      <%= link_to "Back", friends_path ,  class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<%if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class = "thead-dark">
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody id="friends">
    <% @friends.each do |friend| %>
      <%if friend.user == current_user %>
        <tr>
          <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= button_to "Delete", friend, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-outline-danger" %></td>

        </tr>
      <%end %>
    <% end %>
    </tbody>
  </table>
  <%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>
<%else %>
  <div class="jumbotron text-center">
    <h1>Bienvenido a la Lista de Amigos</h1>
    <p class="lead">Para gestionar tu lista de amigos, por favor regístrate o inicia sesión.</p>
    <hr class="my-4">
    <p>Con nuestra aplicación, puedes añadir, editar y eliminar amigos de tu lista fácilmente.</p>
    <%= link_to 'Registrarse', new_user_registration_path, class: 'btn btn-dark btn-lg mx-2' %>
    <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'btn btn-secondary btn-lg mx-2' %>
  </div>
<%end %>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New friend</h1>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
    <br>
    <div>
      <%= link_to "Back to friends", friends_path,  class: "btn btn-secondary"  %>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> |
    <%= @friend.phone %>
  </p>
  <hr class="my-4">
    <%= @friend.twitter %>
  <br>
  </p>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark"  %>
</div>
<div>

  <%#= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friends App", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About us", home_about_path, class: "nav-link"%>
        </li>
        <%if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friend_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
          </li>
        <%else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
          </li>
        <%end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Información</h1>
<p>¡Bienvenido a mi aplicación de Rails! Esta es una aplicación web sencilla que permite a los usuarios gestionar una lista de amigos.</p>

<h2>Características</h2>
<ul>
  <li><strong>Operaciones CRUD:</strong> Puedes crear, leer, actualizar y eliminar entradas en tu lista de amigos.</li>
  <li><strong>Autenticación:</strong> Mi aplicación incluye autenticación de usuarios, permitiendo a los usuarios registrarse, iniciar sesión y cerrar sesión de forma segura.</li>
</ul>

<h2>Operaciones CRUD</h2>
<p>Mi aplicación proporciona una interfaz sencilla e intuitiva para gestionar tu lista de amigos:</p>
<ul>
  <li><strong>Crear:</strong> Añade nuevos amigos a tu lista llenando un formulario sencillo.</li>
  <li><strong>Leer:</strong> Ve los detalles de cada amigo en tu lista.</li>
  <li><strong>Actualizar:</strong> Edita la información de tus amigos si hay algún cambio.</li>
  <li><strong>Eliminar:</strong> Elimina amigos de tu lista si ya no son necesarios.</li>
</ul>

<h2>Autenticación</h2>
<p>Utilizo Devise para la autenticación de usuarios, proporcionando una forma segura y confiable de gestionar las sesiones de usuario. Los usuarios pueden registrarse para una nueva cuenta, iniciar sesión con sus credenciales y cerrar sesión cuando terminen.</p>

<p>Consultas: ignadiasg@gmail.com</p>

app/views/home/index.html.erb
<h1>Hello, mundo</h1>
This is my first Rails Webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <%= notice %>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <title>Friends</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render "home/header"%>
  <div class = "container">
    <br>
    <%if notice %>
      <%= render 'layouts/alerts' %>
    <%end %>
    <%= yield %>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>